from turtle import *
from random import randint
speed(20)
penup()
goto(-140,140)
for step in range(15):
  write(step, align='center')
  right(90)
  forward(10)
  pendown()
  forward(150)
  penup()
  backward(160)
  left(90)
  forward(20)
kirti= Turtle()
kirti.color('red')
kirti.shape('turtle')
kirti.penup()
kirti.goto(-160, 100)
kirti.pendown()
for turn in range(100):
  # kirti.forward(randint(1,5))
  kirti.right(3.6)
roopak= Turtle()
roopak.color('blue')
roopak.shape('turtle')
roopak.penup()
roopak.goto(-160,70)
roopak.pendown()
for turn in range(72):
  roopak.left(5)
amit = Turtle()
amit.shape('turtle')
amit.color('green')
amit.penup()
amit.goto(-160, 40)
amit.pendown()
for turn in range(60):
  amit.right(6)
sirisa = Turtle()
sirisa.shape('turtle')
sirisa.color('orange')
sirisa.penup()
sirisa.goto(-160, 10)
sirisa.pendown()
for turn in range(30):
  sirisa.left(12)
for turn in range(100):
  kirti.forward(randint(1,5))
  roopak.forward(randint(1,5))
  amit.forward(randint(1,5))
  sirisa.forward(randint(1,5))
